dpa99c/cordova-diagnostic-plugin

README.md
Thanks for your plugin! This is incredibly useful for my Ionic app. 
I found a missing parenthesis in the documentation; this PR adds it back.
=> Fixed syntax error in docs for switchToLocationSettings.

README.md, plugin.xml, src/windows/diagnosticProxy.js, www/windows/diagnostic.js
This branch adds support for Windows 10 Mobile. I've updated the README with the Windows particulars, but basically it has all of the functionality of the Android version except for isGpsLocationEnabled(), isNetworkLocationEnabled() & getLocationMode(), which don't really make sense on Windows since it uses a secret-sauce combination of GPS/Network/"undisclosed"/etc. techniques to report the location. The only known issue at this time is that switchToBluetoothSettings() takes the user to the All Settings page of the Settings app rather than to the Bluetooth page. I believe there's a problem with the URI for that page and have so noted it in the code. Microsoft's documentation states that it's "ms-settings-bluetooth:" for Windows 10 Mobile, "ms-settings:bluetooth" for Windows 10 Desktop …
=> Added support for Windows 10 Mobile

plugin.xml
Add NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription to Info.plist via config.xml per iOS 8+ change
from issue https://github.com/dpa99c/cordova-diagnostic-plugin/issues/23
=> requestLocationAuthorization - Can't find variable: error #23

www/android/diagnostic.js
I didn't understand why my app reported not having access to camera since i did give it access and it was actually taking pictures.
Turns out, android M doesn't care much about camera but only about external storage access.
Removing references to camera access fixed my problem.
I tried asking only for camera (and not for storage) and nothing ever happened (no prompt, no new authorization entries in app details).
Also tested on lollipop (5.1.1) and kitkat (4.4.2) and it works fine.
=> Fixed requestCameraAuthorization returning DENIED_ALWAYS when access is granted

src/android/Diagnostic.java
We were having a problem where this plugin would fail on initialization with the below stack trace. I narrowed it down to this block. By wrapping this in a block with fail it seems to be fine.
```System.err: java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10119 nor current process has android.permission.BLUETOOTH.
05-26 16:13:58.271 26276 26396 W System.err:     at android.os.Parcel.readException(Parcel.java:1620)
05-26 16:13:58.271 26276 26396 W System.err:     at android.os.Parcel.readException(Parcel.java:1573)
05-26 16:13:58.271 26276 26396 W System.err:     at android.bluetooth.IBluetooth$Stub$Proxy.isEnabled(IBluetooth.java:848)
05-26 16:13:58.271 26276 26396 W System.err:     at android.bluetooth.BluetoothAdapter.isEnabled(BluetoothAdapter.java:610)
05-26 …
```
=> Prevent Bluetooth Exception On Initialization

plugin.xml
Missing `NSContactsUsageDescription` required for iOS10
=> Adds NSContactsUsageDescription (iOS10)

src/android/Diagnostic.java
(node:65776) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
\platforms\android\src\cordova\plugins\Diagnostic.java:1262: error: strings in switch are not supported in -source 1.6
switch(abi){
^
(use -source 7 or higher to enable strings in switch)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
=>  strings switch not supported in -source 1.6

CHANGELOG.md, package.json, plugin.xml
After upgrading from `3.7.3` to `4.x`, my iOS builds were missing the Camera privacy plist entries (e.g. `NSPhotoLibraryUsageDescription`).
It appears that for the iOS camera module, the `<framework>` and `<config-file target="*-Info.plist">` elements were accidentally nested inside the `<config-file target="config.xml">` element. This PR simply relocates them after the `<js-module>` element (matching the pattern of other iOS modules).
Technically, I should probably be either overriding the default plist values, or disabling the Camera module, since I don't use it, but this change gets my builds working, and seems to be the intention of @dpa99c. Probably just a quick error in the `4.x` refactors.
Thanks for reading!
=> Camera module: de-nest config-file & framework entries

cordova.plugins.diagnostic.d.ts
Today, for example, we are not able to use `motionStatus` constants in a typesafe manner (there is no check on the existence of this or that motion status since the type is `any`)
This PR aims at fixing this.
Conceptually, yes, this is a breaking change in terms of type descriptor (today's `any` has a wider type space than the one I'm proposing)
However, this is for good : people using `window.cordova.plugins.diagnostic.motionStatus.NOT_DETERMINNED` (typo in the name) in their code were not having any error, and now they will have some.
Note that it may help pinpoint migration issues introduced recently (like #230) in case people doesn't read the changelog :-)
=> Describe status constants possible values

README.md
Change `cordova.plugins.diagnostic.hasBluetoothLESupport(successCallback, errorCallback);` for `    cordova.plugins.diagnostic.hasBluetoothSupport(successCallback, errorCallback);` as specified in #### Example usage
Change small error in the documentation for hasBluetoothSupport
=> Fix error in hasBluetoothSupport()

www/android/diagnostic.location.js
On allow "When in use" (approx location)
When `ACCESS_COARSE_LOCATION is GRANTED` by the user but `ACCESS_FINE_LOCATION is `DENIED_ALWAYS`, `getLocationAuthorizationStatus()` will return `DENIED_ALWAYS`.   
This PR will not return `DENIED_ALWAYS` when interpreting the result of the Location Statuses. If one of the status is `GRANTED` it will continue to evaluate the subsequent if/else statements. 
This PR is (especially) relevant for Android 12 as the user is now by default presented with a choice between the two `GRANT` types when `requestLocationAuthorization()` is called. See issue #456.
=> Android 12.0 - API 31 - combineLocationStatuses() Fixes #456

src/android/Diagnostic_External_Storage.java
android getExternalSdCardDetails on API 33 fails as the read/write external storage permissions have been removed.
Update to use the existing permissions check for API < 33, do not request the invalid permissions for API 33+
Backward compatible, non-breaking change.
- [ X] Bugfix
- [X ] Testing has been carried out for the changes have been added
- [ X] No
Tested extensively on my own projects with different API versions to validate behaviour on API below 33 and on API 33+
No changes to existing behaviour
=> fix: android getExternalSdCardDetails on API 33

README.md, src/android/Diagnostic.java, src/android/Diagnostic_External_Storage.java
Listing the external SD cards is currently asking for permissions.
But the SDK 33 permission change made me look more into this, as asking for _MEDIA_ related permissions seems strange.
This permission request has been removed as tests confirm that all SD cards are correctly fetched without them in various Android versions.
Built a testApp with targetSDK 33, installed on emulators API 28, 29, 30, 32, and 33,
Then I checked the SD cards listing is returning correct values, no error, and without asking for any permission.
Tests done in the context of https://github.com/apache/cordova-plugin-file/pull/597.
=> Android: direct getExternalSdCardDetails without permission request

README.md
The way it was written, someone (like me) could understand `enableDebug()` would redirect any log messages (even native ones) from logcat into the JS console. It's not the case, you still need to attach to Android Studio to see logcat detaills.
=> [README] Make it clear debug is about the plugin

src/ios/Diagnostic.m
This PR adds code to check if we're compiling for Mac Catalyst and then disables usage of the CTCellularData module, which is not available on macOS.
Currently apps with this plugin will not build on Mac Catalyst due to the use of CoreTelephony/CTCelluarData, which is not available on macOS. With this change, code will be wrapped in conditions to check for this target and will thus be excluded from Mac Catalyst.
=> Added conditions to not use CTCellularData on Mac Catalyst.

README.md, cordova.plugins.diagnostic.d.ts, src/ios/Diagnostic_Notifications.h, src/ios/Diagnostic_Notifications.m, www/ios/diagnostic.js, www/ios/diagnostic.notifications.js
For bug fixes / features, please check if your PR fulfils the following requirements:
I have implemented the iOS platform functionality for the existing `switchToNotificationSettings` function in the Notifications module, currently only available on Android. On iOS 15.4 or below, the native API to do this was not available, so instead similar to the android implementation, it will take you to the general app settings page instead.
An existing project of mine required the function on both platforms. I have tested it on devices both above and below iOS 15.4.
I have have made sure the original android function had not been affected, as I require both for my project.
=> Added iOS implementation of switchToNotificationSettings function

plugin.xml, src/ios/Diagnostic_Resources.bundle/PrivacyInfo.xcprivacy
No data is collected in accordance to Apple's definition of collected data.
https://developer.apple.com/app-store/app-privacy-details/#data-collection
“Collect” refers to transmitting data off the device in a way that allows you and/or your third-party partners to access it for a period longer than what is necessary to service the transmitted request in real time.
There is one API that requires a declared reason to use, the NSUserDefaults API. The code is in the base Diagnostic utility class so it's available/used regardless of modules instead, but the actual execution path is only ever invoked through the Motion module.
It uses the standard user defaults object which is private to the application. CA92.1 appears to the best reason description, which describes that the SDK reads and …
=> feat(ios): Resource Bundle to provide the Privacy Manifest

src/android/Diagnostic.java
requestCameraAuthorization in API 30 requests WRITE_EXTERNAL_STORAGE, however, if it has not already been granted, it fails because maxSdkPermissionMap was set to 29. This prevents new authorizations from being given for camera use in API 30. 
I increased it to 32 to allow all API < 33 to work.
I have tested it on Android level 9, 11, 12, and 13.
I used it to take a picture and otherwise exercise its functionality and nothing else seems to have changed.
=> Bump WRITE_EXTERNAL_STORAGE to 32 for camera

README.md
`<edit-config>` is the proper way to override the usage description messages, not `<config-file>`.
And removes the `platform` attribute that does neither exist on [`<onfig-file>`](https://cordova.apache.org/docs/en/12.x/plugin_ref/spec.html#config-file) nor on [`<edit-config>`](https://cordova.apache.org/docs/en/12.x/plugin_ref/spec.html#edit-config). 
Defining one same `NS*UsageDescription` with different values gave me the following results:
1. first "expected to override all" value in config.xml through `<config-file>`, then inside one or more plugin.xml from installed plugins: the finally applied value is the one from the last plugin 🤔 
2. first "expected to override all" value in config.xml through `<edit-file>`, then inside one or more …
=> docs: readme to suggest edit-config instead of config-file

src/android/Diagnostic.java, src/android/Diagnostic_Camera.java
Commit f5298057938b4e044ed9d57e3532d59e6cfa0920 added the `TargetApi` import, and then the commit 823f0a0e0c7cd43425e64c60f12b98f9f69cfc0a added the `Manifest` and `Build` imports, but all yet unused.
=> Android: remove unused imports

src/android/Diagnostic_External_Storage.java
[`getAvailableBlocks`](https://developer.android.com/reference/android/os/StatFs#getAvailableBlocks()) and [`getBlockSize`](https://developer.android.com/reference/android/os/StatFs#getBlockSize()) are deprecated since API 18
[`getAvailableBytes`](https://developer.android.com/reference/android/os/StatFs#getAvailableBytes()) is available since API 18
while current `cordova-android` must be [`>=8.0.0`](https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/plugin.xml#L14), so [minSdk 19](https://github.com/apache/cordova-android/blob/rel/8.0.0/framework/AndroidManifest.xml#L22)
=> Android: replace deprecated StatFs functions
