dpa99c/cordova-diagnostic-plugin

README.md
src/ios/Diagnostic.h
src/ios/Diagnostic.m
www/ios/diagnostic.js

Thought it would be fitting to add this.

[iOS] Added function to request or check microphone access authorization.

---

src/ios/Diagnostic.m

Deprecation Warnings Fix

---

www/android/diagnostic.js

customize to add api for requestExternalStorage permission for android

Add API for requestExternalStorage for android

---

README.md
src/ios/Diagnostic.h
src/ios/Diagnostic.m
www/ios/diagnostic.js

Working solution out team have used to implement `switchToLocationSettings` on iOS

add switchToLocationSettings to iOS

---

README.md

I had an issue with this plugin. I always got `DENIED_ALWAYS ` after reinstalling the app and couldn't find why… So I dug in the issues and find one very useful. It could be useful to others so I added extra documentation. 
Issue related: https://github.com/dpa99c/cordova-diagnostic-plugin/issues/191#issuecomment-291467086

Update README.md with information about NOT_REQUESTED & DENIED_ALWAYS statuses for Android

---

README.md

Fix enableDebug() for iOS note

---

README.md

Fix broken reference to locationAuthorizationMode constants because of missing paragraph.

Add doc about locationAuthorizationMode constants

---

README.md

Fix docs referring to NOT_REQUESTED constant

---

cordova.plugins.diagnostic.d.ts

Just fixing some TypeScript definition issues I found while integrating this highly useful plugin

Assorted type corrections

---

package.json

Updating the `minimist` npm package to the latest version to remove security audit, addresses #394  
Testing in emulators to ensure services still prompt as expected.

Bumping minimist package version to resolve security audit

---

README.md

See https://github.com/dpa99c/cordova-diagnostic-plugin/issues/458 
- Add additional information in the docs about platform changes effecting `registerLocationStateChangeHandler()`
- Rename of a accidental chapter/content mismatch  (`registerLocationAccuracyAuthorizationChangeHandler()`)

DOC `registerLocationStateChangeHandler()` resolves #458 

---

README.md
cordova.plugins.diagnostic.d.ts
plugin.xml
scripts/apply-modules.js
src/android/Diagnostic_Airplane_Mode.java
www/android/diagnostic.airplane_mode.js
www/android/diagnostic.js

I am using this in production in my app.
I have tested on several Android devices, spanning mulitple manufacturers and Android versions

Airplane mode

---

package.json

This PR aims to resolve the minimist security issues:
[https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795)
[https://security.snyk.io/vuln/SNYK-JS-MINIMIST-559764](https://security.snyk.io/vuln/SNYK-JS-MINIMIST-559764)
As the [minimist](https://github.com/substack/minimist) Readme points out, these issues where solved on the 1.2.6 package version
Security FIX

Bump minimist to v1.2.6 to prevent security issues

---

README.md
cordova.plugins.diagnostic.d.ts
src/android/Diagnostic.java
www/android/diagnostic.js

Adds Android 12 Bluetooth permissions

Adds Android 12 Bluetooth permissions

---

README.md

Some code fragments were not shown correctly by GitHub engine when after a list.
And typo in `getLocationAuthorizationStatuses` example.
Some more cleanup about line endings (crlf vs lf) and indents (tabs vs spaces).

Correct README code fragments

---

cordova.plugins.diagnostic.d.ts

The Typescript definitions do not match the code of the library and have therefore been adjusted. 
Nothing.
Nothing.
```typescript
// A string array with exactly one element.
[string]
// A string array with zero or more elements. 
string[]
```

Using unlimited arrays in the TypeScript definition

---

README.md
cordova.plugins.diagnostic.d.ts
src/android/Diagnostic.java
src/ios/Diagnostic.h
src/ios/Diagnostic.m
www/android/diagnostic.js
www/ios/diagnostic.js

Tested the implemented API functions on Android & iOS physical devices 
Projects that use the diagnostics plugin functionality have been tested again.

feat: implement checking for accessibility mode

---

README.md

Commit 88dd89a70b99edf18d824da01a5f03075f7597e8 added this example log.

docs: correct example log for Ephemeral permission granted

---

README.md

Commit 823f0a0e0c7cd43425e64c60f12b98f9f69cfc0a added this part of sentence.

docs: remove piece of sentence in readme

---

README.md

use the correct parameter accuracy instead of the undefined variable status in the getLocationAccuracyAuthorization function.

[README] Correct variable name in getLocationAccuracyAuthorization callback
